/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Bmapgallery: typeof import('./src/components/gis/bmapgallery/index.vue')['default']
    Donate: typeof import('./src/components/gis/donate/index.vue')['default']
    EarthquakeMap: typeof import('./src/components/EarthquakeMap.vue')['default']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    LanguageSwitcher: typeof import('./src/components/LanguageSwitcher.vue')['default']
    Mapgallery: typeof import('./src/components/gis/mapgallery/index.vue')['default']
    Maptoolbar: typeof import('./src/components/gis/maptoolbar/index.vue')['default']
    SvgIcon: typeof import('./src/components/svgIcon/index.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
